# Default values for nms-kapacitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: nms-kapacitor

replicaCount: 1

restartPolicy: Always

image:
  repository: zcm9/nms-kapacitor
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: C_20210629141904

env:
  - name: CLOUD_APP_NAME
    value: paas_nms-kapacitor
  - name: NMS_KAPACITOR_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-nms
        key: NMS_KAPACITOR_PORT
  - name: NMS_KAPACITOR_CONTROLLER_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-nms
        key: NMS_KAPACITOR_CONTROLLER_PORT
  - name: NMS_KAPACITOR_SSL_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-nms
        key: NMS_KAPACITOR_SSL_PORT
  - name: NMS_KAPACITOR_MEM
    valueFrom:
      configMapKeyRef:
        name: zcm-env-nms
        key: NMS_KAPACITOR_MEM
  - name: ZCM_MYSQL_VIP
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MYSQL_VIP
  - name: ZCM_MYSQL_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MYSQL_PORT
  - name: ZCM_MYSQL_USER
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MYSQL_USER
  - name: ZCM_MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: zcm-mysql
        key: mysql-root-passwd
  - name: ZCM_SERVER_VIP
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_SERVER_VIP
  - name: NMS_KAPACITOR_VIP
    valueFrom:
      configMapKeyRef:
        name: zcm-env-nms
        key: NMS_KAPACITOR_VIP
  - name: ZCM_SERVER_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_SERVER_PORT
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

resources:
  requests:
    cpu: 0.1
    memory: 128Mi
  limits:
    cpu: 4
    memory: 4096Mi

ports:
  - containerPort: 25593
    protocol: TCP
    name: https
  - containerPort: 8593
    protocol: TCP
    name: http
  - containerPort: 8594
    protocol: TCP
    name: http-controller

volumeMounts:
  - name: localtime
    mountPath: /etc/localtime
    readOnly: True
  - name: zcm-timezone
    mountPath: /etc/timezone
    subPath: timezone
    readOnly: True
  - name: zlogs
    mountPath: /tmp/zlogs
    readOnly: False

volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
  - name: zlogs
    hostPath:
      path: /tmp/zlogs

cm:
  - name: zcm-timezone
    configMap:
      name: zcm-timezone

service:
  type: ClusterIP
  ports:
    - name: https
      port: 25593
      protocol: TCP
      targetPort: 25593
    - name: http
      port: 8593
      protocol: TCP
      targetPort: 8593
    - name: http-controller
      port: 8594
      protocol: TCP
      targetPort: 8594

dnsPolicy: ClusterFirst
clusterIP: None
