apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
    cloud.google.com/neg: '{"ingress":true}'
  name: ingress-nginx-gke-nodeport
  namespace: hogke
spec:
  ports:
    - name: http-gateway
      port: 8001
      protocol: TCP
      targetPort: 8001
      nodePort: 32000
    - name: http-ingress
      port: 8002
      protocol: TCP
      targetPort: 8002
      nodePort: 32001
    - name: https-notuse
      port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 32002
  selector:
    cloud.google.com/gke-nodepool: business-node
    app.kubernetes.io/name: ingress-nginx-gke
  type: LoadBalancer

