apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  name: ingress-nginx-gke-nodeport
  namespace: hogke
spec:
  ports:
    - name: http
      port: 8001
      protocol: TCP
      targetPort: 8001
      nodePort: 32000
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 32001
  selector:
    cloud.google.com/gke-nodepool: business-node
    app.kubernetes.io/name: ingress-nginx-gke
  type: NodePort

