apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
    cloud.google.com/neg: '{"ingress":true}'
  name: ingress-nginx-gke-loadbalancer
  namespace: hogke
spec:
  ports:
    - name: http
      port: 8002
      protocol: TCP
      targetPort: 8002
      nodePort: 32001
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 32002
  selector:
    app.kubernetes.io/name: ingress-nginx-gke
  type: LoadBalancer

