---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: zcm9
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http
      port: 52000
      targetPort: 52000
      protocol: TCP
    - name: https
      port: 25000
      targetPort: 25000
      protocol: TCP
  selector:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
