{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oss-od-web-rc-demo
  labels:
    {{- include "zcm-tpl.labels" . | nindent 4 }}
  annotations:
    networking.gke.io/managed-certificates: "managed-gke-cert"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "gke-ip"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024M"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- range .Values.ingress.annotations }}
      {{- toYaml .rewritePath | nindent 6 }}
      {{- end }}
spec:
  rules:
  - http:
      paths:
      {{- range $index, $topping := .Values.ingress.apps }}
      {{- range $index, $topping2 := $topping.path }}
      - backend:
          service:
            name: {{ $topping.name }}
            port:
              number: {{ $topping.port }}
        path: {{ $topping2.externalPath }}
        pathType: ImplementationSpecific
      {{- end }}
      {{- end }}
  {{- end }}
