apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-role
  apiGroup: rbac.authorization.k8s.io
