# Default values for zcm-zdaasmanager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: zcm-zdaasmanager

replicaCount: 1

restartPolicy: Always

image:
  repository: zcm9/zcm-zdaasmanager
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: C_20210527095213

env:
  - name: LANG
    value: en_US.UTF-8
  - name: CLOUD_APP_NAME
    value: paas_zcm-zdaasmanager
  - name: ZDAAS_MANAGER_DB
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MIDDLE_MANAGER_DB
  - name: ZDAAS_MANAGER_REQURL
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_SERVER_VIP
  - name: ZDAAS_MANAGER_DB_USERNAME
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MYSQL_USER
  - name: ZDAAS_MANAGER_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        key: mysql-root-passwd
        name: zcm-mysql
  - name: ZCM_MYSQL_VIP
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MYSQL_VIP
  - name: ZCM_MYSQL_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MYSQL_PORT
  - name: ZCM_MYSQL_USER
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MYSQL_USER
  - name: ZCM_MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: mysql-root-passwd
        name: zcm-mysql
  - name: ZCM_REDIS_SERVER_LIST
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_REDIS_SERVER_LIST
  - name: ZCM_REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        key: redis-root-passwd
        name: zcm-redis
  - name: ZCM_SERVER_VIP
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_SERVER_VIP
  - name: ZCM_SERVER_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_SERVER_PORT
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

resources:
  requests:
    cpu: 0.1
    memory: 512Mi
  limits:
    cpu: 4
    memory: 4096Mi

ports:
  - containerPort: 52880
    protocol: TCP
    name: http
  - containerPort: 25880
    protocol: TCP
    name: https

volumeMounts:
  - name: localtime
    mountPath: /etc/localtime
    readOnly: True
  - name: zcm-timezone
    mountPath: /etc/timezone
    subPath: timezone
    readOnly: True
  - name: zlogs
    mountPath: /tmp/zlogs
    readOnly: False

volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
  - name: zlogs
    hostPath:
      path: /tmp/zlogs

cm:
  - name: zcm-timezone
    configMap:
      name: zcm-timezone

service:
  type: ClusterIP
  ports:
    - name: http
      port: 52880
      protocol: TCP
      targetPort: 52880
    - name: https
      port: 25880
      protocol: TCP
      targetPort: 25880

dnsPolicy: ClusterFirst
clusterIP: None
