apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    service.alpha.kubernetes.io/app-protocols: '{"helloweb-tls":"HTTPS"}'
  name: oss-od-web-rc
  namespace: hogke
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    zcm-app: oss-od-web-rc
  type: NodePort
