{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "zcm-tpl.name" . -}}
  {{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "zcm-tpl.labels" . | nindent 4 }}
  annotations:
    networking.gke.io/managed-certificates: "managed-gke-cert"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024M"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- range .Values.ingress.annotations }}
      {{- toYaml .rewritePath | nindent 6 }}
      {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        {{- range .Values.ingress.path }}
        - backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
          path: {{ .externalPath }}
        {{- end }}
  {{- end }}
