{{- if eq .Values.global.architecture "ha" }}
apiVersion: v1
data:
  mysql-root-passwd: {{ .Values.secret.mysqlrootpasswd }}
kind: Secret
metadata:
  name: {{ include "zcm-mysql-slave.fullname" . }}
type: {{ .Values.secret.type }}
{{- end }}
