# configure Connaisseur deployment
deployment:
  replicasCount: 3
  image: securesystemsengineering/connaisseur:v2.6.0
  imagePullPolicy: IfNotPresent
  # imagePullSecrets contains an optional list of Kubernetes Secrets, in Connaisseur namespace,
  # that are needed to access the registry containing Connaisseur image.
  # imagePullSecrets:
  # - name: "my-container-secret"
  failurePolicy: Fail  # use 'Ignore' to fail open if Connaisseur becomes unavailable
  # Use 'reinvocationPolicy: IfNeeded' to be called again as part of the admission evaluation if the object
  # being admitted is modified by other admission plugins after the initial webhook call
  # Note that if Connaisseur is invoked a second time, the policy to be applied might change in between.
  # Make sure, your Connaisseur policies are set up to handle multiple mutations of the image originally
  # specified in the manifest, e.g. my.private.registry/image:1.0.0 and my.private.registry/image@sha256:<hash-of-1.0.0-image>
  reinvocationPolicy: Never
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - connaisseur
            topologyKey: kubernetes.io/hostname
          weight: 100
  #annotations:  # uncomment when using Kubernetes prior v1.19
  #  seccomp.security.alpha.kubernetes.io/pod: runtime/default  # uncomment when using Kubernetes prior v1.19
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10001  # remove when using openshift or OKD 4
    runAsGroup: 20001  # remove when using openshift or OKD 4
    seccompProfile:  # remove when using Kubernetes prior v1.19, openshift or OKD 4
      type: RuntimeDefault  # remove when using Kubernetes prior v1.19, openshift or OKD 4
  # PodSecurityPolicy is deprecated as of Kubernetes v1.21, and will be removed in v1.25
  podSecurityPolicy:
    enabled: false
    name: ["connaisseur-psp"]  # list of PSPs to use, "connaisseur-psp" is the project-provided default
  envs: {} # dict of additional environment variables, which will be stored as a secret and injected into the Connaisseur pods
  # Extra config
  extraContainers: []
  extraVolumes: []
  extraVolumeMounts: []

# configure Connaisseur service
service:
  type: ClusterIP
  port: 443

### VALIDATORS ###
# validators are a set of configurations (types, public keys, authentication)
# that can be used for validating one or multiple images (or image signatures).
# they are tied to their respective image(s) via the image policy below. there
# are a few handy validators pre-configured.
validators:
  # static validator that allows each image
  - name: allow
    type: static
    approve: true
  # static validator that denies each image
  - name: deny
    type: static
    approve: false
  # the `default` validator is used if no validator is specified in image policy
  - name: default
    type: notaryv1  # or other supported validator (e.g. "cosign")
    host: notary.docker.io # configure the notary server for notaryv1 or rekor url for cosign
    trust_roots:
    # # the `default` key is used if no key is specified in image policy
    #- name: default
    #  key: |  # enter your public key below
    #    -----BEGIN PUBLIC KEY-----
    #    <add your public key here>
    #    -----END PUBLIC KEY-----
    #cert: |  # in case the trust data host is using a self-signed certificate
    #  -----BEGIN CERTIFICATE-----
    #  ...
    #  -----END CERTIFICATE-----
    #auth:  # credentials in case the trust data requires authentication
    #  # either (preferred solution)
    #  secret_name: mysecret  # reference a k8s secret in the form required by the validator type (check the docs)
    #  # or (only for notaryv1 validator)
    #  username: myuser
    #  password: mypass
  # pre-configured nv1 validator for public notary from Docker Hub
  - name: dockerhub-basics
    type: notaryv1
    host: notary.docker.io
    trust_roots:
      # public key for official docker images (https://hub.docker.com/search?q=&type=image&image_filter=official)
      # !if not needed feel free to remove the key!
      - name: docker-official
        key: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOXYta5TgdCwXTCnLU09W5T4M4r9f
          QQrqJuADP6U7g5r9ICgPSmZuRHP/1AYUfOQW3baveKsT969EfELKj1lfCA==
          -----END PUBLIC KEY-----
      # public key securesystemsengineering repo including Connaisseur images
      # !this key is critical for Connaisseur!
      - name: securesystemsengineering-official
        key: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsx28WV7BsQfnHF1kZmpdCTTLJaWe
          d0CA+JOi8H4REuBaWSZ5zPDe468WuOJ6f71E7WFg3CVEVYHuoZt2UYbN/Q==
          -----END PUBLIC KEY-----
  - name: artifact-registry
    type: cosign
    trust_roots:
      - name: google-artifact-registry
        key: |
          -----BEGIN PUBLIC KEY-----
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCf44y9FSLYeRMr
          PPpMQFZ34mfQl/r3EdBAB+jWxrQwOivfiOjWCxGo2RCf9J6711t7WRnr2c2+fttx
          dlTHgkAa4cHFCDfGjd+7NGOvMJl9j3n2rjmgaLGQVkiCvQcjyKQpupc53OY8yOpB
          W2jTYpkqf3fITaulGcoSTpsDoCb6z99OskJuhzpL+1S7v4VsvgrnU/knQXcAQ4jB
          yBJiIKlr8a3igAYPgZMYAFyfxjVFYQeIzrt8tu1ngtqTPG7wNFrqv6r/YFgTmJg5
          YODOmm2vEE3d7WgyDz8P+v6H2uHNlOBeHwMYDYW97r/xJThchILN5/5sndy+Omf/
          8rDt0IG5AgMBAAECggEABqwpYG60YJJU8XX/ABWjRieFq5fcGll89l8eIXBzbpvO
          3upIxT37A6/jWLmNsksffztNsKELTArhP4/vo8/Uuwp22rEoGroq/xYFnvcJQMsv
          DNNihkY4OszPA929oYmrCC7IRtroJNtBo26cJk40FCjzp8FOC3rTCwaKw5D4b3kS
          XD08ETbzqMvUAjeHePaABbEB5P5vri0sst0m1QYguw/hAT0gborlCVLiQWh812lP
          PLcSOB2B6oPy6nZD9cvaMpNajudn5nGilsypKXDBaGszCa7MZ/7yom0LYBRgKLq/
          XSfFDn5p7wEd6OV2u23JrdJG88TfXbBL7Kvnn9aV3QKBgQDh/hlo+vNhSUsRTM86
          Iv9Ha5aaLtgHyd6lkFAj09/C+RmLCrOaDFLQG6r8BrS6RWh1+T22E5Rgsl7KlzxG
          tPx5mokaLExbwpqwwJoKzSnCDOtKHGfrdX6Z5Ke8yt69Em6aTciN5YjF3KQrN6hj
          FB2+PpYdPjW9IJNJGgKyZmWM2wKBgQC1Hnbv3694z9E6uWUjRjDdfJRRldGMu7I2
          xpbxQPFEsACoxpBEWzsoDggaFrSavX/y/2QxMt8nVcYL09Qf/RWfYLqf9r5bzc5Z
          /9H6aDjl7keCyL57cgZuMLDIg0GSy+m0bdVEl/BB8mpp2pZrzdQVj8q9g8mkwhhq
          KCEzcBdl+wKBgC898wnjC+WWcL7ZE6jPkBXaA82PZVGbfZOWq2oR7IDRmela/1iA
          ov8mCYRN0pHt2Hxw8dmSFj5wiyhGnS8avnydNXPnNr8n2zZ/zLPdV5FdKgKAFak/
          EowRJI9uyUk1BTH0eKxRA1p5WUg/hk/P8LfIVZEfZBR5LtDlQxMQHMJpAoGAD0Tb
          OAu+ikvS0sWQbjHbqsB27I3Z1ah5NL73OK2F6YmA9LmQrgKW8SCFtFVXsnfpUn4P
          X0pvn6xOfu7DwlKewQnxkczGbYzjKZk0hYzFxzSYWME9tcB+JEn8jVrra0m/kRN1
          WEwK2DRsnjHsXnhCufKeX+29USN/1Ws+qUx43IMCgYEAwalsJrGKt863Tz1dNrbL
          Pb9SgWrq220holaw+AP4R0E3WAwHHWjHsFDHXDP7zCZaRYy58qB0pXqBulMNYW6r
          WShxBWOcD7s5EaA5Oz73+wo/Sj7jemolX3uYUqPFs0cR6qdIQ/shReJymflstrI7
          74OdcrCQC1AupzEOarerpXc=
          -----END PUBLIC KEY-----
### IMAGE POLICY ###
# the image policy ties validators and images together whereby always only the most specific rule (pattern)
# is applied. specify if and how images should be validated by which validator via the validator name.
policy:
  - pattern: "*:*"
    validator: deny
  - pattern: "europe-west2-docker.pkg.dev/wct-oss-dev/zcm9/*:*"
    validator: artifact-registry
    with:
      trust_root: google-artifact-registry
#  - pattern: "europe-west2-docker.pkg.dev/wct-oss-dev/hogke/*:*"
#    validator: artifact-registry
#    with:
#      trust_root: google-artifact-registry

# in detection mode, deployment will not be denied, but only prompted
# and logged. this allows testing the functionality without
# interrupting operation.
detectionMode: false

# namespaced validation allows to restrict the namespaces that will be subject to Connaisseur verification.
# when enabled, based on namespaced validation mode ('ignore' or 'validate')
# - either all namespaces with label "securesystemsengineering.connaisseur/webhook=ignore" are ignored
# - or only namespaces with label "securesystemsengineering.connaisseur/webhook=validate" are validated.
# warning: enabling namespaced validation, allows roles with edit permission on a namespace to disable
# validation for that namespace
namespacedValidation:
  enabled: false
  mode: ignore  # 'ignore' or 'validate'

# automatic child approval determines how admission of Kubernetes child resources is handled by Connaisseur.
# per default, Connaisseur validates and mutates all resources, e.g. deployments, replicaSets, pods, and
# automatically approves child resources of those to avoid duplicate validation and inconsistencies with the
# image policy. when disabled Connaisseur will only validate and mutate pods. check the docs for more
# information.
# NOTE: configuration of automatic child approval is in EXPERIMENTAL state.
automaticChildApproval:
  enabled: true

# debug: true


# The "logLevel" configuration option adds a partial redundancy to the `debug` setting.
# Removing the `debug` setting is a breaking change though - we are going to remove the `debug` setting in the context of a larger refactoring to avoid multiple breaking releases.
# Option to configure the log level. Either one of `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`. Defaults to `INFO`
logLevel: INFO

# alerting is implemented in form of simple POST requests with json payload
# you can use and/or adapt the predefined Slack/OpsGenie/Keybase templates and the examples below
# to channel alert notifications to Slack/OpsGenie/Keybase or create a custom template for a customized alert
# payload to use with a simple POST request to the receiver_url to receive alerts.
# Parameters you can use in your templates are "alert_message", "priority", "connaisseur_pod_id", "cluster",
# "timestamp", "request_id" and "images" each one basically meaning what their names indicate
#
# Below is an example config

#alerting:
#  cluster_identifier: example-cluster-staging-europe # defaults to "not specified"
#  admit_request:
#    templates:
#      # <template> needs to be chosen such that <template>.json matches one of the file names
#      # in the ./alert_payload_templates directory
#      - template: opsgenie #REQUIRED!
#        receiver_url: https://api.eu.opsgenie.com/v2/alerts #REQUIRED!
#        priority: 4 #(defaults to 3)
#        custom_headers: ["Authorization: GenieKey <Your-Genie-Key>"]
#        payload_fields:
#          responders:
#            - username: "testuser@testcompany.de"
#              type: user
#          visibleTo:
#            - username: "testuser@testcompany.de"
#              type: user
#          tags:
#            - "deployed_an_image"
#        fail_if_alert_sending_fails: True  # (defaults to False, turning it to True will make Connaisseur deny your
#                                           # deployment (even in detection mode))
#      - template: slack #REQUIRED!
#        receiver_url: https://hooks.slack.com/services/<Your-Slack-Hook-Path>
#        priority: 1
#  reject_request:
#    templates:
#      - template: keybase  #REQUIRED!
#        receiver_url: https://bots.keybase.io/webhookbot/<Your-Keybase-Hook-Token>
#        fail_if_alert_sending_fails: True
