nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  host: gke.lumos.hyperoptic.com
  apps:
  - name: oss-od-web-rc-demo
    port: 8080
    annotations:
      - rewritePath: rewrite /oss/bc/od_web/appInfo/status(.*)$ /opb/appInfo/status$1 break;
      - rewritePath: rewrite /oss/static/oss_core/od(.*)$ /oss_core/od$1 break;
      - rewritePath: rewrite /oss/oss_core/od(.*)$ /oss_core/od$1 break;
    path:
      - externalPath: /oss/bc/od_web/appInfo/status
      - externalPath: /oss/static/oss_core/od
      - externalPath: /oss/oss_core/od
    pathType: Prefix
  - name: demo2
    port: 8080
    annotations:
      - rewritePath: rewrite /aaa/bbb/ccc(.*)$ /AAA/BBB/CCC$1 break;
      - rewritePath: rewrite /ddd/eee/fff(.*)$ /DDD/EEE/FFF$1 break;
      - rewritePath: rewrite /ggg/hhh/iii(.*)$ /GGG/HHH/III$1 break;
    path:
      - externalPath: /aaa/bbb/ccc
      - externalPath: /ddd/eee/fff
      - externalPath: /ggg/hhh/iii
    pathType: Prefix
