nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  host: oss-gke.lumos.hyperoptic.com
  apps:
  - name: oss-ofm-async
    port: 8080
    annotations:
      - rewritePath: rewrite /oss/bc/od_web/appInfo/status(.*)$ /opb/appInfo/status$1 break;
    path:
      - externalPath: /oss/bc/ofm_async/appInfo/status
    pathType: Prefix
