# Default values for zcm-zcamp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: zcm-zcamp

replicaCount: 1

restartPolicy: Always

image:
  repository: zcm9/zcm-zcamp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: C_20210527093857

env:
  - name: LANG
    value: en_US.UTF-8
  - name: CLOUD_APP_NAME
    value: paas_zcm-zcamp
  - name: APM_INIT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_APM_INIT
  - name: ZCAMP_JDBC_URL
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCAMP_JDBC_URL
  - name: ZCAMP_JDBC_USR
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MYSQL_USER
  - name: ZCAMP_JDBC_PASS
    valueFrom:
      secretKeyRef:
        key: mysql-root-passwd
        name: zcm-mysql
  - name: ZCAMP_ANSIBLE_REST_SERVER
    value: "http://zcm-zcamp-rest-server:8081/rest"
  - name: ZCAMP_JEDIS_HOST
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_REDIS_SERVER_LIST
  - name: ZCAMP_JEDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        key: redis-root-passwd
        name: zcm-redis
  - name: ZCM_SSC_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-cluster
        key: ZCM_SSC_PORT
  - name: ZCM_RESOURCE_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-cluster
        key: ZCM_RESOURCE_PORT
  - name: ZCM_CMDB_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_CMDB_PORT
  - name: ZCM_NGINX_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_NGINX_PORT
  - name: LOG_LEVEL_PROFILE
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: LOG_LEVEL_PROFILE
  - name: ZCM_MIDWARE_ZCACHE_REST
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MIDWARE_ZCACHE_REST
  - name: ZCM_MIDWARE_ZMQ_REST
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MIDWARE_ZMQ_REST
  - name: ZCM_MIDWARE_ZDAAS_REST
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MIDWARE_ZDAAS_REST
  - name: ZCM_SERVER_VIP
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_SERVER_VIP
  - name: ZCM_SERVER_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_SERVER_PORT
  - name: ZCM_SERVER_SSL_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_SERVER_SSL_PORT
  - name: REDIS_SERIALIZER_TYPE
    value: "json"
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

resources:
  requests:
    cpu: 0.1
    memory: 512Mi
  limits:
    cpu: 4
    memory: 4096Mi

ports:
  - containerPort: 52860
    protocol: TCP
    name: http
  - containerPort: 25860
    protocol: TCP
    name: https

volumeMounts:
  - name: localtime
    mountPath: /etc/localtime
    readOnly: True
  - name: zcm-timezone
    mountPath: /etc/timezone
    subPath: timezone
    readOnly: True
  - name: collectd
    mountPath: /root/collectd
    readOnly: False
  - name: supervisord
    mountPath: /root/supervisord
    readOnly: False

volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
  - name: collectd
    emptyDir: {}
  - name: supervisord
    emptyDir: {}

cm:
  - name: zcm-timezone
    configMap:
      name: zcm-timezone

service:
  type: ClusterIP
  ports:
    - name: http
      port: 52860
      protocol: TCP
      targetPort: 52860
    - name: https
      port: 25860
      protocol: TCP
      targetPort: 25860

dnsPolicy: ClusterFirst
clusterIP: None
